[general]
import = ["./themes/catppuccin-mocha.toml"]

[terminal]
shell = {program = "/run/current-system/sw/bin/zsh"}

[window]
padding = { x=28, y=28 }
#opacity = 0.9
decorations = "Buttonless"
option_as_alt="Both"

[font]
size = 16
normal      = { family="Iosevka Nerd Font Mono", style="Regular" }
bold        = { family="Iosevka Nerd Font Mono", style="Bold" }
italic      = { family="Iosevka Nerd Font Mono", style="Italic" }
bold_italic = { family="Iosevka Nerd Font Mono", style="Bold Italic" }
